-- ============================================================
-- E-COMMERCE SALES & CUSTOMER ANALYTICS
-- Business Analysis Queries
-- ============================================================

USE ecommerce_project;

-- Revenue definition used throughout:
-- Revenue = product price × quantity
-- Cancelled orders are excluded unless explicitly stated.


-- ============================================================
-- SECTION 1: CORE BUSINESS ANALYSIS
-- ============================================================


-- Q1. What is the total revenue generated from valid orders?

SELECT 
    SUM(p.price * oi.quantity) AS total_revenue
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled';


-- Q2. What is the monthly revenue trend?

SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(p.price * oi.quantity) AS monthly_revenue
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled'
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY month;


-- Q3. What is the average order value (AOV)?

SELECT 
    ROUND(
        SUM(p.price * oi.quantity) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled';


-- Q4. How much revenue does each product category generate?

SELECT 
    c.category_name,
    SUM(p.price * oi.quantity) AS revenue
FROM categories c
JOIN products p 
    ON c.category_id = p.category_id
JOIN order_items oi 
    ON p.product_id = oi.product_id
JOIN orders o 
    ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
GROUP BY c.category_id, c.category_name
ORDER BY revenue DESC;


-- Q5. How much revenue is generated by customers from each city?

SELECT 
    c.city,
    SUM(p.price * oi.quantity) AS revenue
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled'
GROUP BY c.city
ORDER BY revenue DESC;


-- Q6. What is the distribution of orders by status?

SELECT 
    status,
    COUNT(*) AS total_orders,
    ROUND(
        COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders),
        2
    ) AS percentage_of_orders
FROM orders
GROUP BY status
ORDER BY total_orders DESC;


-- Q7. Which payment methods generate the highest paid amount?

SELECT 
    payment_method,
    COUNT(*) AS total_paid_transactions,
    SUM(amount) AS paid_amount,
    ROUND(
        SUM(amount) * 100.0 /
        (
            SELECT SUM(amount)
            FROM payments
            WHERE payment_status = 'Paid'
        ),
        2
    ) AS percentage_of_paid_amount
FROM payments
WHERE payment_status = 'Paid'
GROUP BY payment_method
ORDER BY paid_amount DESC;


-- Q8. What is the sales performance of each product?

SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS quantity_sold,
    SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi 
    ON p.product_id = oi.product_id
JOIN orders o 
    ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;
