-- ============================================================
-- E-COMMERCE SALES & CUSTOMER ANALYTICS
-- Business Analysis Queries
-- ============================================================

USE ecommerce_project;

-- Revenue definition used throughout:
-- Revenue = product price × quantity
-- Cancelled orders are excluded unless explicitly stated.


-- ============================================================
-- SECTION 1: CORE BUSINESS ANALYSIS
-- ============================================================


-- Q1. What is the total revenue generated from valid orders?

SELECT 
    SUM(p.price * oi.quantity) AS total_revenue
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled';


-- Q2. What is the monthly revenue trend?

SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(p.price * oi.quantity) AS monthly_revenue
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled'
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY month;


-- Q3. What is the average order value (AOV)?

SELECT 
    ROUND(
        SUM(p.price * oi.quantity) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled';


-- Q4. How much revenue does each product category generate?

SELECT 
    c.category_name,
    SUM(p.price * oi.quantity) AS revenue
FROM categories c
JOIN products p 
    ON c.category_id = p.category_id
JOIN order_items oi 
    ON p.product_id = oi.product_id
JOIN orders o 
    ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
GROUP BY c.category_id, c.category_name
ORDER BY revenue DESC;


-- Q5. How much revenue is generated by customers from each city?

SELECT 
    c.city,
    SUM(p.price * oi.quantity) AS revenue
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled'
GROUP BY c.city
ORDER BY revenue DESC;


-- Q6. What is the distribution of orders by status?

SELECT 
    status,
    COUNT(*) AS total_orders,
    ROUND(
        COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders),
        2
    ) AS percentage_of_orders
FROM orders
GROUP BY status
ORDER BY total_orders DESC;


-- Q7. Which payment methods generate the highest paid amount?

SELECT 
    payment_method,
    COUNT(*) AS total_paid_transactions,
    SUM(amount) AS paid_amount,
    ROUND(
        SUM(amount) * 100.0 /
        (
            SELECT SUM(amount)
            FROM payments
            WHERE payment_status = 'Paid'
        ),
        2
    ) AS percentage_of_paid_amount
FROM payments
WHERE payment_status = 'Paid'
GROUP BY payment_method
ORDER BY paid_amount DESC;


-- Q8. What is the sales performance of each product?

SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS quantity_sold,
    SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi 
    ON p.product_id = oi.product_id
JOIN orders o 
    ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;

-- ============================================================
-- SECTION 2: CUSTOMER ANALYSIS
-- ============================================================


-- Q9. How much revenue has each customer generated?

SELECT
    c.customer_id,
    c.customer_name,
    COUNT(DISTINCT o.order_id) AS valid_orders,
    COALESCE(SUM(p.price * oi.quantity), 0) AS customer_spend
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
    AND o.status <> 'Cancelled'
LEFT JOIN order_items oi
    ON o.order_id = oi.order_id
LEFT JOIN products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY customer_spend DESC;


-- Q10. Who are the top 5 customers by spending?

SELECT
    c.customer_id,
    c.customer_name,
    SUM(p.price * oi.quantity) AS customer_spend
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled'
GROUP BY c.customer_id, c.customer_name
ORDER BY customer_spend DESC
LIMIT 5;


-- Q11. Which customers are repeat customers?

SELECT
    c.customer_id,
    c.customer_name,
    COUNT(DISTINCT o.order_id) AS valid_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.status <> 'Cancelled'
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT o.order_id) > 1
ORDER BY valid_orders DESC;


-- Q12. Which customers have no valid orders?

SELECT
    c.customer_id,
    c.customer_name,
    c.city,
    c.signup_date
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
    AND o.status <> 'Cancelled'
WHERE o.order_id IS NULL;


-- Q13. What are each customer's first and latest valid order dates?

SELECT
    c.customer_id,
    c.customer_name,
    MIN(o.order_date) AS first_order_date,
    MAX(o.order_date) AS latest_order_date
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.status <> 'Cancelled'
GROUP BY c.customer_id, c.customer_name
ORDER BY first_order_date;


-- Q14. Which customers spend more than the average customer?

WITH customer_spending AS (
    SELECT
        c.customer_id,
        c.customer_name,
        COALESCE(SUM(p.price * oi.quantity), 0) AS customer_spend
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
        AND o.status <> 'Cancelled'
    LEFT JOIN order_items oi
        ON o.order_id = oi.order_id
    LEFT JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
)
SELECT
    customer_id,
    customer_name,
    customer_spend
FROM customer_spending
WHERE customer_spend > (
    SELECT AVG(customer_spend)
    FROM customer_spending
)
ORDER BY customer_spend DESC;


-- Q15. What is the customer revenue performance by city?

SELECT
    c.city,
    COUNT(DISTINCT c.customer_id) AS customers_with_valid_orders,
    COUNT(DISTINCT o.order_id) AS valid_orders,
    SUM(p.price * oi.quantity) AS revenue,
    ROUND(
        SUM(p.price * oi.quantity) /
        COUNT(DISTINCT c.customer_id),
        2
    ) AS revenue_per_customer
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled'
GROUP BY c.city
ORDER BY revenue DESC;


-- Q16. How can customers be segmented based on total spending?

WITH customer_spending AS (
    SELECT
        c.customer_id,
        c.customer_name,
        COALESCE(SUM(p.price * oi.quantity), 0) AS customer_spend
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
        AND o.status <> 'Cancelled'
    LEFT JOIN order_items oi
        ON o.order_id = oi.order_id
    LEFT JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
),
customer_segments AS (
    SELECT
        customer_id,
        customer_name,
        customer_spend,
        CASE
            WHEN customer_spend >= 7000 THEN 'High Value'
            WHEN customer_spend >= 3000 THEN 'Medium Value'
            ELSE 'Low Value'
        END AS customer_segment
    FROM customer_spending
)
SELECT
    customer_segment,
    COUNT(*) AS total_customers,
    SUM(customer_spend) AS segment_revenue,
    ROUND(AVG(customer_spend), 2) AS average_customer_spend,
    ROUND(
        SUM(customer_spend) * 100.0 /
        (SELECT SUM(customer_spend) FROM customer_segments),
        2
    ) AS revenue_contribution_percentage
FROM customer_segments
GROUP BY customer_segment
ORDER BY segment_revenue DESC;

-- ============================================================
-- SECTION 3: PRODUCT & INVENTORY ANALYSIS
-- ============================================================


-- Q17. Which products sold the highest quantity?

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY quantity_sold DESC;


-- Q18. Which products generated the highest revenue?

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS quantity_sold,
    SUM(p.price * oi.quantity) AS product_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY product_revenue DESC;


-- Q19. Which products have never been purchased through a valid order?

SELECT
    p.product_id,
    p.product_name
FROM products p
LEFT JOIN order_items oi
    ON p.product_id = oi.product_id
LEFT JOIN orders o
    ON oi.order_id = o.order_id
    AND o.status <> 'Cancelled'
WHERE o.order_id IS NULL;


-- Q20. What is the average product price within each category?

SELECT
    c.category_name,
    ROUND(AVG(p.price), 2) AS average_product_price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name
ORDER BY average_product_price DESC;


-- Q21. Which products are priced above their category average?

WITH product_prices AS (
    SELECT
        p.product_id,
        p.product_name,
        c.category_name,
        p.price,
        AVG(p.price) OVER (
            PARTITION BY p.category_id
        ) AS category_avg_price
    FROM products p
    JOIN categories c
        ON p.category_id = c.category_id
)
SELECT
    product_id,
    product_name,
    category_name,
    price,
    ROUND(category_avg_price, 2) AS category_avg_price
FROM product_prices
WHERE price > category_avg_price
ORDER BY category_name, price DESC;


-- Q22. Which actively selling products may face inventory risk?

SELECT
    p.product_id,
    p.product_name,
    p.stock,
    SUM(oi.quantity) AS quantity_sold,
    SUM(p.price * oi.quantity) AS revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.status <> 'Cancelled'
  AND p.stock < 50
GROUP BY
    p.product_id,
    p.product_name,
    p.stock
ORDER BY p.stock ASC;


-- Q23. How are product categories performing overall?

WITH category_metrics AS (
    SELECT
        c.category_id,
        c.category_name,
        COUNT(DISTINCT p.product_id) AS total_products,
        ROUND(AVG(p.price), 2) AS average_product_price
    FROM categories c
    LEFT JOIN products p
        ON c.category_id = p.category_id
    GROUP BY c.category_id, c.category_name
),
sales_metrics AS (
    SELECT
        p.category_id,
        SUM(oi.quantity) AS quantity_sold,
        SUM(p.price * oi.quantity) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY p.category_id
)
SELECT
    cm.category_id,
    cm.category_name,
    cm.total_products,
    COALESCE(sm.quantity_sold, 0) AS quantity_sold,
    COALESCE(sm.revenue, 0) AS revenue,
    cm.average_product_price
FROM category_metrics cm
LEFT JOIN sales_metrics sm
    ON cm.category_id = sm.category_id
ORDER BY revenue DESC;

-- ============================================================
-- SECTION 4: ADVANCED ANALYSIS & WINDOW FUNCTIONS
-- ============================================================


-- Q24. Rank products by revenue within each category.

WITH product_revenue AS (
    SELECT
        c.category_name,
        p.product_id,
        p.product_name,
        SUM(p.price * oi.quantity) AS revenue
    FROM categories c
    JOIN products p
        ON c.category_id = p.category_id
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY
        c.category_name,
        p.product_id,
        p.product_name
)
SELECT
    category_name,
    product_name,
    revenue,
    RANK() OVER (
        PARTITION BY category_name
        ORDER BY revenue DESC
    ) AS category_rank
FROM product_revenue
ORDER BY category_name, category_rank;


-- Q25. Find the top 3 revenue-generating products in each category.

WITH product_revenue AS (
    SELECT
        c.category_name,
        p.product_id,
        p.product_name,
        SUM(p.price * oi.quantity) AS revenue
    FROM categories c
    JOIN products p
        ON c.category_id = p.category_id
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY
        c.category_name,
        p.product_id,
        p.product_name
),
ranked_products AS (
    SELECT
        category_name,
        product_name,
        revenue,
        ROW_NUMBER() OVER (
            PARTITION BY category_name
            ORDER BY revenue DESC
        ) AS product_rank
    FROM product_revenue
)
SELECT
    category_name,
    product_name,
    revenue,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category_name, product_rank;


-- Q26. Rank customers according to their total spending.

WITH customer_spending AS (
    SELECT
        c.customer_id,
        c.customer_name,
        COALESCE(SUM(p.price * oi.quantity), 0) AS customer_spend
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
        AND o.status <> 'Cancelled'
    LEFT JOIN order_items oi
        ON o.order_id = oi.order_id
    LEFT JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
)
SELECT
    customer_id,
    customer_name,
    customer_spend,
    DENSE_RANK() OVER (
        ORDER BY customer_spend DESC
    ) AS spending_rank
FROM customer_spending
ORDER BY spending_rank, customer_name;


-- Q27. Who are the top 2 customers by spending within each city?

WITH customer_spending AS (
    SELECT
        c.customer_id,
        c.customer_name,
        c.city,
        COALESCE(SUM(p.price * oi.quantity), 0) AS customer_spend
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
        AND o.status <> 'Cancelled'
    LEFT JOIN order_items oi
        ON o.order_id = oi.order_id
    LEFT JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY
        c.customer_id,
        c.customer_name,
        c.city
),
ranked_customers AS (
    SELECT
        customer_id,
        customer_name,
        city,
        customer_spend,
        ROW_NUMBER() OVER (
            PARTITION BY city
            ORDER BY customer_spend DESC
        ) AS city_rank
    FROM customer_spending
)
SELECT
    customer_id,
    customer_name,
    city,
    customer_spend,
    city_rank
FROM ranked_customers
WHERE city_rank <= 2
ORDER BY city, city_rank;


-- Q28. What is the running cumulative revenue by month?

WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS month,
        SUM(p.price * oi.quantity) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    WHERE o.status <> 'Cancelled'
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
)
SELECT
    month,
    revenue,
    SUM(revenue) OVER (
        ORDER BY month
    ) AS cumulative_revenue
FROM monthly_revenue
ORDER BY month;


-- Q29. What percentage of total revenue is contributed by each category?

WITH category_revenue AS (
    SELECT
        c.category_name,
        SUM(p.price * oi.quantity) AS revenue
    FROM categories c
    JOIN products p
        ON c.category_id = p.category_id
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY c.category_id, c.category_name
)
SELECT
    category_name,
    revenue,
    ROUND(
        revenue * 100.0 / SUM(revenue) OVER (),
        2
    ) AS revenue_contribution_percentage
FROM category_revenue
ORDER BY revenue DESC;


-- Q30. What is the month-over-month revenue growth?

WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS month,
        SUM(p.price * oi.quantity) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    WHERE o.status <> 'Cancelled'
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
),
revenue_comparison AS (
    SELECT
        month,
        revenue,
        LAG(revenue) OVER (
            ORDER BY month
        ) AS previous_month_revenue
    FROM monthly_revenue
)
SELECT
    month,
    revenue,
    previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue) * 100.0 /
        previous_month_revenue,
        2
    ) AS mom_growth_percentage
FROM revenue_comparison
ORDER BY month;

-- ============================================================
-- SECTION 5: BUSINESS CASE STUDY & EXECUTIVE ANALYSIS
-- ============================================================


-- Q31. Which customer segment generates the highest business value?

WITH customer_spending AS (
    SELECT
        c.customer_id,
        c.customer_name,
        COALESCE(SUM(p.price * oi.quantity), 0) AS customer_spend
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
        AND o.status <> 'Cancelled'
    LEFT JOIN order_items oi
        ON o.order_id = oi.order_id
    LEFT JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id, c.customer_name
),
customer_segments AS (
    SELECT
        customer_id,
        customer_name,
        customer_spend,
        CASE
            WHEN customer_spend >= 7000 THEN 'High Value'
            WHEN customer_spend >= 3000 THEN 'Medium Value'
            ELSE 'Low Value'
        END AS customer_segment
    FROM customer_spending
)
SELECT
    customer_segment,
    COUNT(*) AS total_customers,
    SUM(customer_spend) AS segment_revenue,
    ROUND(AVG(customer_spend), 2) AS avg_customer_spend,
    ROUND(
        SUM(customer_spend) * 100.0 /
        SUM(SUM(customer_spend)) OVER (),
        2
    ) AS revenue_contribution_percentage
FROM customer_segments
GROUP BY customer_segment
ORDER BY segment_revenue DESC;


-- Q32. What does customer retention look like?

WITH customer_orders AS (
    SELECT
        c.customer_id,
        c.customer_name,
        COUNT(DISTINCT o.order_id) AS valid_orders
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
        AND o.status <> 'Cancelled'
    GROUP BY c.customer_id, c.customer_name
),
customer_types AS (
    SELECT
        customer_id,
        customer_name,
        valid_orders,
        CASE
            WHEN valid_orders = 0 THEN 'No Valid Orders'
            WHEN valid_orders = 1 THEN 'One-Time'
            ELSE 'Repeat'
        END AS customer_type
    FROM customer_orders
)
SELECT
    customer_type,
    COUNT(*) AS total_customers,
    ROUND(
        COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER (),
        2
    ) AS percentage_of_customers
FROM customer_types
GROUP BY customer_type
ORDER BY total_customers DESC;


-- Q33. How does the product portfolio perform by revenue segment?

WITH product_performance AS (
    SELECT
        p.product_id,
        p.product_name,
        COALESCE(
            SUM(
                CASE
                    WHEN o.status <> 'Cancelled'
                    THEN p.price * oi.quantity
                    ELSE 0
                END
            ), 0
        ) AS product_revenue,
        COALESCE(
            SUM(
                CASE
                    WHEN o.status <> 'Cancelled'
                    THEN oi.quantity
                    ELSE 0
                END
            ), 0
        ) AS quantity_sold
    FROM products p
    LEFT JOIN order_items oi
        ON p.product_id = oi.product_id
    LEFT JOIN orders o
        ON oi.order_id = o.order_id
    GROUP BY p.product_id, p.product_name
),
product_segments AS (
    SELECT
        product_id,
        product_name,
        product_revenue,
        quantity_sold,
        CASE
            WHEN product_revenue = 0 THEN 'No Sales'
            WHEN product_revenue >= 5000 THEN 'High Revenue'
            WHEN product_revenue >= 2000 THEN 'Medium Revenue'
            ELSE 'Low Revenue'
        END AS revenue_segment
    FROM product_performance
)
SELECT
    revenue_segment,
    COUNT(*) AS total_products,
    SUM(quantity_sold) AS total_quantity_sold,
    SUM(product_revenue) AS segment_revenue
FROM product_segments
GROUP BY revenue_segment
ORDER BY segment_revenue DESC;


-- Q34. What are the company's headline business KPIs?

SELECT
    (SELECT COUNT(*) FROM customers) AS total_customers,

    (SELECT COUNT(*) FROM orders) AS total_orders,

    (
        SELECT COUNT(*)
        FROM orders
        WHERE status <> 'Cancelled'
    ) AS valid_orders,

    (
        SELECT COUNT(*)
        FROM orders
        WHERE status = 'Cancelled'
    ) AS cancelled_orders,

    (
        SELECT SUM(p.price * oi.quantity)
        FROM orders o
        JOIN order_items oi
            ON o.order_id = oi.order_id
        JOIN products p
            ON oi.product_id = p.product_id
        WHERE o.status <> 'Cancelled'
    ) AS total_revenue,

    ROUND(
        (
            SELECT SUM(p.price * oi.quantity)
            FROM orders o
            JOIN order_items oi
                ON o.order_id = oi.order_id
            JOIN products p
                ON oi.product_id = p.product_id
            WHERE o.status <> 'Cancelled'
        )
        /
        (
            SELECT COUNT(*)
            FROM orders
            WHERE status <> 'Cancelled'
        ),
        2
    ) AS average_order_value,

    (SELECT COUNT(*) FROM products) AS total_products,

    (
        SELECT SUM(oi.quantity)
        FROM order_items oi
        JOIN orders o
            ON oi.order_id = o.order_id
        WHERE o.status <> 'Cancelled'
    ) AS total_quantity_sold;


-- Q35. Executive business analysis:
-- Consolidate the most decision-relevant findings from the project.

WITH category_revenue AS (
    SELECT
        c.category_name,
        SUM(p.price * oi.quantity) AS revenue
    FROM categories c
    JOIN products p
        ON c.category_id = p.category_id
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.status <> 'Cancelled'
    GROUP BY c.category_id, c.category_name
),
customer_spending AS (
    SELECT
        c.customer_id,
        COALESCE(SUM(p.price * oi.quantity), 0) AS customer_spend
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
        AND o.status <> 'Cancelled'
    LEFT JOIN order_items oi
        ON o.order_id = oi.order_id
    LEFT JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id
)
SELECT
    (SELECT SUM(revenue) FROM category_revenue) AS total_revenue,

    (
        SELECT category_name
        FROM category_revenue
        ORDER BY revenue DESC
        LIMIT 1
    ) AS top_category,

    (
        SELECT revenue
        FROM category_revenue
        ORDER BY revenue DESC
        LIMIT 1
    ) AS top_category_revenue,

    (
        SELECT ROUND(
            SUM(
                CASE
                    WHEN customer_spend >= 7000
                    THEN customer_spend
                    ELSE 0
                END
            ) * 100.0 / SUM(customer_spend),
            2
        )
        FROM customer_spending
    ) AS high_value_customer_revenue_pct,

    (
        SELECT COUNT(*)
        FROM products p
        WHERE p.stock < 50
          AND EXISTS (
              SELECT 1
              FROM order_items oi
              JOIN orders o
                  ON oi.order_id = o.order_id
              WHERE oi.product_id = p.product_id
                AND o.status <> 'Cancelled'
          )
    ) AS active_products_below_50_stock;
